[package]
name = "ekur"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[dependencies]
anyhow = "1.0.95"
bitflags = "2.8.0"
clap = { version = "4.5.28", features = ["derive"] }
ddsfile = "0.5.2"
image = { version = "0.25.5", features = ["png"], default-features = false }
image_dds = { version = "0.7.1", default-features = false, features = [
  "image",
  "ddsfile",
] }
infinite-rs = { version = "0.8.4", features = ["derive"] }
num_enum = "0.7.3"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = { version = "1.0.138", features = ["preserve_order"] }
walkdir = "2.5.0"
indexmap = { version = "2.7.1", features = ["serde"] }
serde_with = { version = "3.12.0", features = ["base64"] }

[profile.release]
lto = "fat"
