schema_version = "1.0.0"

id = "ekur"
version = "1.1.6"
name = "Ekur"
tagline = "A multi-purpose importer for Halo Infinite"
maintainer = "Surasia <https://github.com/Surasia>"
type = "add-on"
tags = ["Import-Export", "Pipeline"]

blender_version_min = "4.3.0"
license = ["SPDX:GPL-3.0-or-later"]

paths_exclude_pattern = ["__pycache__/", "/.git/", "/*.zip", "/.venv"]

[permissions]
files = "For selecting JSON files containing coating data"
network = "Downloading and saving strings and Ekur executable"
