[project]
name = "ekuraddon"
version = "0.4.0"
description = "A multi-purpose importer for Halo Infinite."
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["fake-bpy-module-latest"]

[tool.pyright]
venvPath = "."
venv = ".venv"
exclude = [".venv"]
reportInvalidTypeForm = false
reportIncompatibleMethodOverride = false
reportImplicitOverride = false

[tool.ruff]
line-length = 100
