name: Cargo test/clippy/build

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        profile: ["release", "dev"]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Update Rust
        run: rustup update

      - name: Build
        run: cargo build --manifest-path "./ekur/Cargo.toml" --profile ${{ matrix.profile }}

      - name: Check clippy
        run: cargo clippy --manifest-path "./ekur/Cargo.toml"
      
      - name: Upload artifact (Windows)
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: ekur-${{ matrix.profile }}-${{ matrix.os }}
          path: ekur/target/${{ matrix.profile }}/ekur.exe

      - name: Upload artifact (Linux)
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: ekur-${{ matrix.profile }}-${{ matrix.os }}
          path: ekur/target/${{ matrix.profile }}/ekur

